#!/bin/bash

corPadrao="\033[0m"
preto="\033[0;30m"
vermelho="\033[0;31m"
verde="\033[0;32m"
marrom="\033[0;33m"
azul="\033[0;34m"
purple="\033[0;35m"
cyan="\033[0;36m"
cinzaClaro="\033[0;37m"
pretoCinza="\033[1;30m"
vermelhoClaro="\033[1;31m"
verdeClaro="\033[1;32m"
amarelo="\033[1;33m"
azulClaro="\033[1;34m"
purpleClaro="\033[1;35m"
cyanClaro="\033[1;36m"
branco="\033[1;37m"

x="teste"
menu ()
{
while true $x != "teste"
do
clear
echo "================================================"
tput setaf 8 ; tput setab 5 ; tput bold ; printf '%30s%s%-15s\n' "DROPBEAR ANDERSONTLS" ; tput sgr0
echo -e "\033[01;34m•>>>>> (CRIADOR ANDERSONTLS) \033[01;34m"
echo -e "\033[01;34m•>>>>> (@kroz44) \033[01;34m"
echo""
echo -e "1)\033[01;34m•>>>>> (INSTALAR DROPBEAR) \033[01;34m"
echo""
echo -e "2)\033[01;33m•>>>>> (REMOVER DROPBEAR)\033[0m"
echo ""
echo -e "3)\033[01;33m•>>>>> (ATUALIZAR SITEMA)\033[0m"
echo ""
echo -e "4)\033[01;33m•>>>>> (PARA SQUID NO UBUNTU 14.04)\033[0m"
echo""
echo -e "5)\033[01;33m•>>>>> (PARA SQUID NO DEBIAM,UBUNTU 16)\033[0m"
echo""
echo -e "6)\033[01;33m•>>>>> (REINICIAR DROPBEAR)\033[0m"
echo""
echo -e "7)\033[01;33m•>>>>> (CORRIGIR ERROS DO SERVIDOR)\033[0m"
echo""
echo -e "8)\033[01;33m•>>>>> (SAIR DO SCRIPT)\033[0m"
echo ""
echo "================================================"

echo "Digite a opção desejada:"
read x
echo "Opção informada ($x)"
echo "================================================"

case "$x" in 


    1)
      echo "INSTALANDO DROPBEAR AGUARDE..."
      apt-get install update
      apt-get install dropbear -y
      apt-get install nano
      rm /etc/default/dropbear
      cd /root
      wget https://raw.githubusercontent.com/andinhotutors/dropbear/master/dropbear
      mv dropbear /etc/default
      service dropbear start
      apt-get install ssh -y
      sleep 5
      
echo "================================================"
;;
    2)
      echo "REMOVENDO DROPBEAR"
      echo "DIGITE dropbear PARA REMOVER"
      read nome
      apt-get remove --purge $nome
      apt-get remove dropbear
      apt-get autoremove
      sleep 5
echo "================================================"
;;
   3)
      echo "Atualizando sistema..."
      apt-get update
      apt-get upgrade -y
      sleep 5
echo "================================================"
;;
   4)
      echo "PARANDO SQUID..."
      service squid3 stop
      service squid stop
      sleep 5
echo "================================================"
;;      
   5)
      echo "PARANDO SQUID..."
      /etc/init.d/squid3 stop
      /etc/init.d/squid3 stop
      sleep 5
echo "================================================"
;;      
   6)  
      echo "REINICIANDO DROPBEAR..." 
      service dropbear restart
      /etc/init.d/dropbear restart
      sleep 5
echo "================================================"
;;
   7) 
      echo "Reparando..."
      dpkg --configure -a
      sleep 5

echo "================================================"
 ;;     
    8)
      echo "saindo..."
      sleep 5
      clear;
      exit;
echo "================================================"
;;

*)
        echo "Opção inválida!"
esac
done

}
menu







     
